site_name: Lucky Project
theme:
  logo: img/project-management.png
  favicon: img/project-management.png

  features:
    - content.code.copy
    - toc.integrate
    - navigation.top
    - navigation.prune
    - navigation.tabs
    - navigation.sevtions
    - search.highlight
    - search suggest
    - content.code.anitation
  
  name: material
  
  palette:
  - scheme: purple
    toggle:
    icon: material/toggle-switch-off-outline
    name: Switch to dark mode
    primary: 
    accent: purple
    scheme: slate
  toggle:
    icon: material/toggle-switch
    name: Switch to light mode
    primary: teal
    accent: line

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/yanglucky_aja/
    - icon: fontawesome/brands/github
      link: https://github.com/LukizCookiez/Lucky-MkDocss
